name: CI-core

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: "${{ matrix.os }}"

    env:
      DEVITO_ARCH: "${{ matrix.arch }}"
      DEVITO_OPENMP: ${{ matrix.openmp }}
      DEVITO_BACKEND: "core"
      OMP_NUM_THREADS: 2
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           py36-gcc49-openmp,
           py37-gcc5-openmp,
           py38-gcc6-openmp,
           py36-gcc7-openmp,
           py37-gcc7-noopenmp,
           py37-gcc8-openmp,
           py38-gcc9-openmp,
           py37-osx,
           docker-devito
        ]
        include:
        - name: py36-gcc49-openmp
          python-version: 3.6
          os: ubuntu-16.04
          arch: "gcc-4.9"
          openmp: 1

        - name: py37-gcc5-openmp
          python-version: 3.7
          os: ubuntu-16.04
          arch: "gcc-5"
          openmp: 1

        - name: py38-gcc6-openmp
          python-version: 3.8
          os: ubuntu-16.04
          arch: "gcc-6"
          openmp: 1

        - name: py36-gcc7-openmp
          python-version: 3.6
          os: ubuntu-16.04
          arch: "gcc-7"
          openmp: 1

        - name: py37-gcc7-noopenmp
          python-version: 3.7
          os: ubuntu-16.04
          arch: "gcc-7"
          openmp: 0

        - name: py37-gcc8-openmp
          python-version: 3.7
          os: ubuntu-16.04
          arch: "gcc-8"
          openmp: 1

        - name: py38-gcc9-openmp
          python-version: 3.8
          os: ubuntu-16.04
          arch: "gcc-9"
          openmp: 1

        - name: py37-clang-osx
          python-version: 3.7
          os: macos-latest
          arch: "osx"
          openmp: 0

        - name: docker-devito
          python-version: 3.6
          os: ubuntu-16.04
          arch: "gcc"
          openmp: 1

    steps:
    - name: check
      run: |
        printenv
